language: python

branches:
  only:
    - master
    - /^\d+\.\d+\.X$/

cache:
  directories:
    - $HOME/.cache/pip
    - .hypothesis

matrix:
  include:
    # Main tests on supported Python versions.
    - python: "3.6"
      dist: bionic
      env: TOXENV=py36
    - python: "3.7"
      dist: bionic
      env: TOXENV=py37
    - python: "3.8"
      dist: bionic
      env: TOXENV=py38
    - python: "pypy3.6-7.2.0"
      dist: bionic
      env: TOXENV=pypy

    # Linting, docs, and other non-test stuff.
    - python: "3.8"
      dist: bionic
      env: TOXENV=lint
    - python: "3.8"
      dist: bionic
      env: TOXENV=docs
    - python: "3.8"
      dist: bionic
      env: TOXENV=packaging
    - python: "3.8"
      dist: bionic
      env: TOXENV=h2spec

install:
  - _travis/install.sh
script:
  - export PATH=$PATH:$PWD/bin/
  - tox -- --hypothesis-profile travis
