language: python

branches:
  only:
    - master
    - /^\d+\.\d+\.X$/

cache:
  directories:
    - $HOME/.cache/pip
    - .hypothesis

matrix:
  include:
    # Main tests on supported Python versions.
    - python: "2.7"
      dist: trusty
      env: TOXENV=py27
    - python: "3.4"
      dist: trusty
      env: TOXENV=py34
    - python: "3.5"
      dist: trusty
      env: TOXENV=py35
    - python: "3.6"
      dist: trusty
      env: TOXENV=py36
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37
    - python: "3.8"
      dist: xenial
      env: TOXENV=py38
    - python: "pypy-5.3.1"
      dist: trusty
      env: TOXENV=pypy

    # Linting, docs, and other non-test stuff.
    - python: "3.7"
      dist: xenial
      env: TOXENV=lint
    - python: "3.7"
      dist: xenial
      env: TOXENV=docs
    - python: "3.7"
      dist: xenial
      env: TOXENV=packaging
    - python: "3.6"
      env: TOXENV=h2spec

install:
  - _travis/install.sh
script:
  - export PATH=$PATH:$PWD/bin/
  - tox -- --hypothesis-profile travis
